In [1]:
import pandas as pd
import json
import time
import matplotlib.pyplot as plt
import re

%matplotlib inline

In [4]:
import requests

url = "https://zillow-com1.p.rapidapi.com/propertyExtendedSearch"

querystring = {"location":"nashville, tn","home_type":"Houses"}

headers = {
	"X-RapidAPI-Host": "zillow-com1.p.rapidapi.com",
	"X-RapidAPI-Key": ""
}

In [5]:
all_houses = pd.DataFrame()
for page in range (10, 20):
    querystring = {"location":"nashville, tn","home_type":"Houses", "status_type":"ForSale", "page":page}
    response = requests.get(url, headers=headers, params=querystring)
    print (response)
    for prop in range (0,40):
        house = pd.DataFrame(response.json()["props"][prop])
        all_houses = pd.concat([all_houses, house])
        
all_houses

<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>
<Response [200]>

IndexError: list index out of range

In [7]:
all_houses

,dateSold,propertyType,lotAreaValue,address,daysOnZillow,price,listingDateTime,longitude,latitude,contingentListingType,...,zpid,listingSubType,imgSrc,livingArea,bathrooms,lotAreaUnit,country,currency,bedrooms,hasImage
is_FSBA,None,SINGLE_FAMILY,1.46,"1015 Tulip Grove Rd, Hermitage, TN 37076",-1,425000,None,-86.59299,36.18796,None,...,41108405,True,https://photos.zillowstatic.com/fp/27e81f348a5...,1550,2,acres,USA,USD,4,True
is_FSBA,None,SINGLE_FAMILY,6969.6,"5902 Morrow Rd, Nashville, TN 37209",-1,499900,None,-86.85982,36.16192,None,...,41112643,True,https://photos.zillowstatic.com/fp/63061ed715d...,672,1,sqft,USA,USD,2,True
is_FSBA,None,SINGLE_FAMILY,1.5,"112 High Estes, Nashville, TN 37215",-1,3390000,None,-86.84064,36.091423,None,...,67620536,True,https://photos.zillowstatic.com/fp/fb8a9e065cf...,6247,6,acres,USA,USD,5,True
is_FSBA,None,SINGLE_FAMILY,10454.4,"2933 Brantley Dr, Antioch, TN 37013",-1,404000,None,-86.61999,36.074127,None,...,41186164,True,https://photos.zillowstatic.com/fp/48cab295f2d...,1571,2,sqft,USA,USD,4,True
is_FSBA,None,SINGLE_FAMILY,5662.8,"5433 Daniel Ray Dr, Whites Creek, TN 37189",-1,428000,None,-86.78867,36.280266,None,...,71268564,True,https://photos.zillowstatic.com/fp/6791cae95cb...,1432,3,sqft,USA,USD,3,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
is_newHome,None,SINGLE_FAMILY,None,"The York Plan, Parkhaven",-1,534990,None,-86.63733,36.195103,None,...,2073572051,True,https://photos.zillowstatic.com/fp/5c8294c5eb3...,1861,3,None,USA,USD,2,True
is_newHome,None,SINGLE_FAMILY,6969.6,"515 31st Ave N, Nashville, TN 37209",-1,1100000,None,-86.82183,36.15529,None,...,41116622,True,https://photos.zillowstatic.com/fp/678a058b0c3...,2725,3,sqft,USA,USD,4,True
is_newHome,None,SINGLE_FAMILY,None,"The Brookemeade Plan, Parkhaven",-1,549990,None,-86.63733,36.195103,None,...,2073572052,True,https://photos.zillowstatic.com/fp/07f41b8a085...,2168,3,None,USA,USD,2,True
is_FSBA,None,SINGLE_FAMILY,0.25,"2710 Delaware Ave, Nashville, TN 37209",-1,775000,None,-86.81773,36.156563,None,...,41116727,True,https://photos.zillowstatic.com/fp/971d8660200...,1056,2,acres,USA,USD,3,True
is_FSBA,None,SINGLE_FAMILY,8276.4,"1742 17th Ave N, Nashville, TN 37208",-1,975000,None,-86.8103,36.179546,None,...,41098072,True,https://photos.zillowstatic.com/fp/46fdcb88f19...,869,1,sqft,USA,USD,2,True

In [8]:
all_houses.to_csv('all_houses_2')

In [9]:
type(response)

requests.models.Response

In [10]:
len(response.json())

4

In [11]:
response.json()["resultsPerPage"]

40

In [12]:
response.json().keys()

dict_keys(['props', 'resultsPerPage', 'totalResultCount', 'totalPages'])

In [14]:
all_data = pd.DataFrame(response.json())

In [15]:
all_data.to_csv('all_data_2')

In [16]:
test = pd.read_csv("all_data_2")

In [18]:
test

,Unnamed: 0,props,resultsPerPage,totalResultCount,totalPages
0,0,"{'dateSold': None, 'propertyType': 'SINGLE_FAM...",40,602,16
1,1,"{'dateSold': None, 'propertyType': 'SINGLE_FAM...",40,602,16